### PR TITLE
[Bugfix] Remove word value from ParameterLength attribute

### PR DESCRIPTION
**Pull request by Ishaangandhi**
Morbig currently incorrectly parses the # as the identifier name, then puts the actual identifier name in the ParameterLength variable_attribute type. https://github.com/colis-anr/morbig/pull/121 fixes that issue, and this pull request updates the AST to reflect those changes.

Currently, Morsmall, when used to convert from Morbig, converts `${#x}` as
```
[{ value =
   (Simple ([],
      [{ value = [(Variable ("#", (ParameterLength [])))];
         position =
         { start_p =
           { pos_fname = "parse_string_morbig"; pos_lnum = 1; pos_bol = 0;
             pos_cnum = 5 };
           end_p =
           { pos_fname = "parse_string_morbig"; pos_lnum = 1; pos_bol = 0;
             pos_cnum = 5 }
           }
         }
        ]
      ));
   position =
   { start_p =
     { pos_fname = "parse_string_morbig"; pos_lnum = 1; pos_bol = 0;
       pos_cnum = 5 };
     end_p =
     { pos_fname = "parse_string_morbig"; pos_lnum = 1; pos_bol = 0;
       pos_cnum = 5 }
     }
   }
  ]
```

Notice, the original variable `x` is gone entirely!

This is being used for the SMOOSH project with @mgree

### CODE REVIEW

**Comment by Niols** [comment]
Hello @Ishaangandhi, and thank you!

We'll have to wait for morbig on that one, but other than that it can be merged as far as I'm concerned.
There will be a bit of conflict (as I just merged #11) to resolve, but I can't do it right now.

I'm a bit curious to see where and how it's used in SMOOSH!

**Comment by mgree** [comment]
Hi @Niols! Hope you're keeping well.

The plan is to have Smoosh be able to Morbig as its primary parser. There are a lot of unsatisfying things about libdash this will fix:

- Unsafe C
- Passing around unmanaged strings and pointers for managing libdash context
- No good way to have the dash parser expand and print `PS1` and `PS2` using Smoosh's state
- FFI means no compilation to JS to run on folks' browsers (though there are other things blocking this, too)

But beyond all those reasons, Morbig + Smoosh should yield the "standardiest" shell one could hope for, which feels like a reason in itself.

That said, for Smoosh to use Morbig in a running shell, we'll need some kind of callback mechanism for prompting. (I have some memory of discussing this with @yurug at some point, maybe at OOPSLA 2018?) If we patch Morbig to have an "interactive" interface in addition to its existing one, would you want a PR, or should we keep it in a fork?

**Comment by Niols** [comment]
> Hi @Niols! Hope you're keeping well.

Hi @mgree! I am, actually (except for the part where I have a PhD these to write). I hope you are too!

> The plan is to have Smoosh be able to Morbig as its primary parser. There are a lot of unsatisfying things about libdash this will fix:
> 
>     * Unsafe C
> 
>     * Passing around unmanaged strings and pointers for managing libdash context
> 
>     * No good way to have the dash parser expand and print `PS1` and `PS2` using Smoosh's state
> 
>     * FFI means no compilation to JS to run on folks' browsers (though there are other things blocking this, too)

So you're planning on compiling the whole Morbig + Smoosh to JS? Using js_of_ocaml, or BuckleScript (I think it's called ReScript now)? That's very exciting! But indeed, that means that all the dependencies must also be compilable to JS which can become pretty complicated sometimes. I am pretty sure there would be some work needed to split Morbig into a JS-compilable unit and the full version. Sounds feasible though!

> But beyond all those reasons, Morbig + Smoosh should yield the "standardiest" shell one could hope for, which feels like a reason in itself.

I agree, I find that very satisfactory and exciting.

> That said, for Smoosh to use Morbig in a running shell, we'll need some kind of callback mechanism for prompting. (I have some memory of discussing this with @yurug at some point, maybe at OOPSLA 2018?) If we patch Morbig to have an "interactive" interface in addition to its existing one, would you want a PR, or should we keep it in a fork?

Personally, I think this would be a great enhancement of Morbig. I have been wanting to add that for a while now, in a project to then write a Shell in OCaml. That last part has now been made obsolete by Smoosh, but I would love to see Morbig include this feature; I think it is somewhat necessary if we want to pretend to be a fully usable parser for such an interactive language as Shell.

**Comment by Ishaangandhi** [comment]
> Personally, I think this would be a great enhancement of Morbig. I have been wanting to add that for a while now, in a project to then write a Shell in OCaml. That last part has now been made obsolete by Smoosh, but I would love to see Morbig include this feature; I think it is somewhat necessary if we want to pretend to be a fully usable parser for such an interactive language as Shell.

Awesome, it would be nice to be able to contribute the code upstream.

By the way, https://github.com/colis-anr/morbig/pull/121 is now merged!

**Comment by Niols** [comment]
Yup, I've seen the merge in Morbig, and it's now done here. Thank you very much for the PR!

**Comment by Ishaangandhi** [comment]
Thank you, @Niols !

**Comment by mgree** [comment]
Great to see this all happening! 👍 Also glad, of course, that things are going well (thesis writing aside). 

My main goal with JS compilation is to get the shtepper fully into the client's browser, which lets me do more computationally interesting things without concern for my modest server's health!

Glancing at the dependencies, what in morbig/morsmall might block JS compilation? My (naive) understanding is that avoiding `Obj` and the FFI is enough... but I haven't looked into the details for either of the OCaml-to-JS compilers.

A nearly equivalent approach would be to use [Browsix](https://browsix.org/) or something similar.

**Comment by Niols** [comment]
I don't specifically know about other projects, but I've been using js_of_ocaml quite a bit.

- `Obj`, indeed, is a problem (because the internal representation is not the same), except for simple functions like `Obj.magic` (because it's only its type that is interesting).

-  That means `Marshall` is also a problem because it relies on the internal representation. Actually, Morbig uses Marshall so this will be a problem.

- Then some `Unix` functions are also problematic (of course, because a browser is not a Unix system).

- And then, the main problem is that, with the transitive closure of your dependencies, the chances to hit one of these problems gets quite hard.

The solutions are:

- If it is coming from code in the tool itself, you split the tool in two. We could have `libmorbig` and `libmorbig.unix` (or something like that) that extends it with Unix/Marshall/Obj-specific functions. The `morbig` tool would use the latter. The former would be transpilable to JS.

- If it is coming from the dependencies, get rid of them. Morbig does not have many dependencies and most of them add additional features so we could easily extract them to `libmorbig.unix`. The only big dependency would be Menhir. Menhir itself has very few dependencies (since it aims at being a very core package). I can't guarantee that it is not using non-JS-compatible functions, but since it is in so many projects, I think I would have encountered the project by now.

I didn't know about Browsix; that's funny! I'll have a look.

By the way, you do have your shtepper in the browser now, right? But I suspect it's using server-side computation?

**Comment by mgree** [comment]
Hmm... `Marshal`. Right. I hadn't thought about! So long as we don't touch that code at runtime, we might be fine. A problem for another day. 😀 

Yes, the Shtepper just runs on the server. It's a performance bottleneck *and* a security liability... what's not to love? 🙄

**Pull request merged**
